### PR TITLE
Create be_by.json

### PR DESCRIPTION
**Pull request by Gazmanovich**
I think this mod need to be translated from 1,17 to 1,20 into belarusian!

### CODE REVIEW

**Comment by RedLime** [comment]
LGTM, but currently 1.17 version is not maintaining at this time :(

**Comment by Gazmanovich** [comment]
So, it need to translate to other versions with separate pull requests?

> LGTM, but currently 1.17 version is not maintaining at this time :(

**Comment by RedLime** [comment]
yeah can you make pr for 1.20 branch?

**Comment by Gazmanovich** [comment]
> yeah can you make pr for 1.20 branch?

Already made

**Pull request closed without merging**
