### PR TITLE
Add resource pack-based customization

### PR DESCRIPTION
**Pull request by invokekitty**
This PR adds the ability to add custom armor and item bars using a resource pack, an example resource pack is included in the `example_resourcepack` directory. This would close issue #20 and make it much easier for mod and modpack makers to add their own armors. 
Currently this system only supports static armor and item entries, however the previous coded api remains to add dynamic entries that depend on the ItemStack. Ive made this on 1.21 initially but i would be glad to backport these changes if needed.

### CODE REVIEW

**Review by RedLime — COMMENTED** [review]
Could you make texture selection to separate each part(full, half, outline, outline_half)?

**Comment by invokekitty** [comment]
I could do that, although it would require changing parts of the original APIs code as i would have to include that data in TextureOffset

**Comment by invokekitty** [comment]
should I still do it?

**Comment by RedLime** [comment]
yeah, of course. also mojang has split the armor texture recently, so it would be make sense. 

so like:
```json
  "render": { 
     "full": {
        "texture": "detailab:textures/armor_bar.png", 
        "texture_width": 128, 
        "texture_height": 128, 
        "offset": [27, 9]
     },
     "half" {
        ...
     }
   }
```

**Comment by invokekitty** [comment]
Okay sure, gonna do that

**Comment by invokekitty** [comment]
i'll try to keep it as backwards-compatible as possible

**Comment by RedLime** [comment]
yeah, that also would be great

**Comment by invokekitty** [comment]
Should I mark the old constructors as deprecated? Since now it takes 4 `BarRenderManager.Texture`s instead of the single texture + offset stuff, i kept the old ones around for backward compatibility

**Comment by invokekitty** [comment]
Also im going to test the resource pack functionality now with the changes don't merge yet

**Comment by RedLime** [comment]
No, that doesn't need to be deprecated.
also, please make as draft if it's not done yet :P

**Comment by invokekitty** [comment]
Another question: Since you can use multiple textures now, should i make the `outline` and `outline_half` fields in the armor json optional and default to the standard outline?

**Comment by RedLime** [comment]
Oh yeah that would be great

**Comment by invokekitty** [comment]
I've tested it and it works well, should be ready now

**Comment by RedLime** [comment]
Thanks a lot! I will review and test it myself tomorrow.
if it's works as well, I will merge it and release the new version.

**Comment by invokekitty** [comment]
fixed some small things i found while looking over my code

**Comment by invokekitty** [comment]
btw i fixed an issue i noticed in the bar rendering code so this PR should fix #55 too

**Comment by invokekitty** [comment]
Hii, have you already tested this?

**Comment by RedLime** [comment]
Sorry, I was busy recently 😅
I will test it today

**Review by RedLime — APPROVED** [review]

**Comment by invokekitty** [comment]
yippiee, should i work on a 1.20.1 backport once this is merged, as it is kind of an lts version?

**Comment by RedLime** [comment]
I don't have planned to release backports, and I'm working on v3.0.0 for multi-loader support

**Comment by RedLime** [comment]
I've planned this release on 1.21.2 release, but there's so many changes with JsonDataLoader class which needs custom codec stuff.
So will be pushed this after fix that.

**Pull request merged**
